name: michelle_plugin
description: A flutter plugin project that can update widget tree and state dynamically.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  crypto: ^3.0.1
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  plugin:
    platforms:
      android:
        package: com.ttm.michelle_plugin
        pluginClass: MichellePlugin
      ios:
        pluginClass: MichellePlugin